global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_prometheus_io_scrape
  - action: keep
    regex: ^__meta_kubernetes_pod_annotation_prometheus_io_scrape
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_prometheus_io_path
  - action: replace
    source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
    target_label: __address__
    regex: (.+)
    replacement: https://$1
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_prometheus_io_scheme
  - action: keep
    regex: ^__meta_kubernetes_pod_annotation_prometheus_io_scheme